name: CI test build

on:
  push:
      branches:
        - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*

    - name: Get current time
      uses: MyJetTools/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DD HH:mm:ss
        utcOffset: "+00:00"
        
    - name: Build
      run: dotnet build --configuration Release /p:AssemblyVersion=0.0.${{ github.run_number }}
    - name: Test
      run: dotnet test --no-build --configuration Release
    - name: ls
      run: ls

    - name: Publish Service
      run: dotnet publish --no-build ./src/Web.Test3ds.csproj --configuration Release --output ./publish-api

    - name: Check Service dir
      run: ls ./publish-api
      
    - name: Publish image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        path: ./publish-api
        registry: ghcr.io
        repository: ${{ secrets.ORG_NAME }}/web.test3ds/web.test3ds-test
        tags: latest
        build_args: app_version=web.test3ds-test:latest,app_compilation_date=${{ steps.current-time.outputs.formattedTime }}

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: cd /home/monfex/Services/Web.Test3ds && docker-compose pull && docker-compose up -d
